# -*- coding: utf-8 -*-
"""Lenet_5_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6FMNNDoU_5D4gVr9h_3I_8ITsNZr1Zo
"""

import tensorflow
from tensorflow import keras
from keras.layers import Dense,Conv2D,Flatten,AveragePooling2D
from keras.datasets import mnist
from keras import Sequential



"""# ***LeNet Architecture***"""

model= Sequential()
#use activation function tanh
#for tanh use reason : in 1989 when yann lecun create this model that time best activetion function is tanh

model.add(Conv2D(6,kernel_size=(5,5),padding='valid',activation='tanh',input_shape=(32,32,1)))
model.add(AveragePooling2D(pool_size=(2,2),strides=2,padding='valid'))

model.add(Conv2D(16,kernel_size=(5,5),padding='valid',activation='tanh'))
model.add(AveragePooling2D(pool_size=(2,2), strides=2, padding='valid'))

model.add(Flatten())
#fullyconnected layer

model.add(Dense(120,activation='tanh'))
model.add(Dense(84,activation='tanh'))
model.add(Dense(10,activation='softmax'))

model.summary()