# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qxywajJzShv1kkkIbKH88zelR3f02q5
"""



from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image # If you need other image preprocessing functions from keras

img = image.load_img("/2.jpg",target_size=(200,200))

import matplotlib.pyplot as plt

plt.imshow(img)

type(img)

datagenerate = ImageDataGenerator(
    rotation_range=40,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,

)

img = image.img_to_array(img)

type(img)

img.shape

input_batch = img.reshape(1,200,200,3)





import os

# ... (rest of your code) ...

# Before calling datagenerate.flow(), create the directory if it doesn't exist
if not os.path.exists('aug'):
    os.makedirs('aug')

i = 0
for output in datagenerate.flow(input_batch, batch_size=1, save_to_dir='aug'):
    i = i + 1
    if i == 10:
        break # Changed 'brake' to 'break'

input_batch.shape

